trigger: triage
title: Triage Issue
description: Explain the status of your triaging this particular issue.
surfaces:
- issue
steps:
- type: form
  style: embedded
  body:
  - type: dropdown
    attributes:
      label: Triage Status
      description: Select the current triage status of this issue
      options:
      - label: 游릭 Complete
        value: 游릭
      - label: 游리 Started
        value: 游리
      - label: 游댮 Not Started
        value: 游댮
  - type: textarea
    attributes:
      label: Triage Notes
      description: Describe what has been done to triage this issue
      placeholder: "Example: I started validation on this by..."
  actions:
    - submit: "Triage"
